[target.riscv32imac-unknown-none-elf]
runner = "probe-rs run --chip=esp32c5 --preverify --always-print-stacktrace --no-location"

[env]
DEFMT_LOG = "info"

[build]
target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]
